export const TERRAIN_SIZE = 220
export const BRUSH_SIZE_RANGE = { min: 2, max: 40 }
export const BRUSH_STRENGTH_SCALE = 0.12
export const BRUSH_STRENGTH_STEP = 0.1
export const BRUSH_FALLOFF_STEP = 0.1
export const BRUSH_PREVIEW_HEIGHT = 8
export const STRENGTH_RING_MIN_FACTOR = 0.2
export const FALLOFF_ARC_DEGREES = 60
export const FALLOFF_RADIUS_FACTOR = 0.6
export const HEIGHT_EXPORT_EPSILON = 0.0001
export const UNDO_MAX_HISTORY = 10
